#!/usr/bin/env python3
"""Generate Android adaptive icon layers from assets/icon.png (requires Pillow)."""

import argparse
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "android/app/src/main/res"
BACKGROUND = "#121121"
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
VIEWPORT_DP = 108
ARTWORK_WIDTH_DP = 62


def extract_artwork():
    """Remove the existing tile, not just its transparent outer corners.

    This crop is specific to the 1024px source: it encloses the ribbon while
    excluding the tile's noisy rounded border. The dark tile's blue channel is
    below 48 here; the ribbon's interior is above 80. A soft blue-channel key
    preserves antialiased edges without retaining a second rounded square.
    """
    with Image.open(ROOT / "assets/icon.png") as source:
        if source.size != (1024, 1024):
            raise ValueError("Source artwork changed: review crop and color key first")
        artwork = source.convert("RGBA").crop((80, 200, 944, 824))
    key = artwork.getchannel("B").point(
        lambda blue: max(0, min(255, round((blue - 48) * 255 / 32)))
    )
    artwork.putalpha(ImageChops.multiply(artwork.getchannel("A"), key))
    bounds = artwork.getbbox()
    if bounds is None:
        raise ValueError("No ribbon found in source artwork")
    return artwork.crop(bounds)


def generate_resources():
    artwork = extract_artwork()
    resources = {}
    for density, scale in DENSITIES.items():
        size = round(VIEWPORT_DP * scale)
        width = round(ARTWORK_WIDTH_DP * scale)
        height = round(width * artwork.height / artwork.width)
        ribbon = artwork.resize((width, height), Image.Resampling.LANCZOS)
        foreground = Image.new("RGBA", (size, size))
        foreground.alpha_composite(ribbon, ((size - width) // 2, (size - height) // 2))
        output = BytesIO()
        foreground.save(output, format="PNG", optimize=True)
        resources[f"drawable-{density}/ic_launcher_foreground.png"] = output.getvalue()

    resources["values/ic_launcher_colors.xml"] = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/generate-android-icons.py. -->\n'
        '<resources>\n'
        f'    <color name="ic_launcher_background">{BACKGROUND}</color>\n'
        '</resources>\n'
    ).encode()
    resources["mipmap-anydpi-v26/ic_launcher.xml"] = (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/generate-android-icons.py. -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/ic_launcher_background" />\n'
        '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
        '</adaptive-icon>\n'
    ).encode()
    return resources


def matches(path, expected):
    if not path.exists():
        return False
    if path.suffix == ".png":
        # Compare decoded pixels: PNG compression can differ across Pillow versions.
        with Image.open(path) as actual, Image.open(BytesIO(expected)) as wanted:
            return (actual.mode, actual.size, actual.tobytes()) == (
                wanted.mode, wanted.size, wanted.tobytes()
            )
    return path.read_bytes() == expected


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify checked-in resources without writing")
    args = parser.parse_args()
    stale = []
    for relative, content in generate_resources().items():
        path = RES / relative
        if args.check:
            if not matches(path, content):
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
            print(path.relative_to(ROOT))
    if stale:
        parser.exit(1, "Outdated or missing icon resources:\n" + "\n".join(stale) + "\n")
    if args.check:
        print("Adaptive icon resources are up to date.")


if __name__ == "__main__":
    main()
